FROM node:latest

WORKDIR /usr/src/app
ENV GOOGLE_APPLICATION_CREDENTIALS="sa-key.json"

COPY package.json package-lock.json sa-key.json .npmrc ./

# authenticate with artifact registry
RUN npm install -g google-artifactregistry-auth
RUN npm run artifactregistry-login

# install force resolutions package
RUN npm install -g npm-force-resolutions

RUN npm install

COPY . .

EXPOSE 4000

ENTRYPOINT [ "npm", "run", "start:dev" ]