apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: docker-registry
      serviceAccountName: gateway
      containers:
        - name: gateway
          image: communicator
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: dev
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  key: key
                  name: jwt-auth
            # rabbitmq
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_ACCESS_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000

          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 20
