apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "308"
    konghq.com/plugins: cors
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
spec:
  tls:
    - hosts:
        - dev-gateway-communicator.lootlog.pl
      secretName: tls
  ingressClassName: kong
  rules:
    - host: dev-gateway-communicator.lootlog.pl
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway
                port:
                  number: 4000
