apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yml
  - deployment.yml
  - ingress.yml
  - istio.yml
  - hpa.yml
images:
  - name: communicator
    newName: test/projectid/test-image
    newTag: test
