name: Build Docker image and publish to the repository
env:
  IMAGE_NAME: communicator_websocket-gateway
  REPO_URL: rg.pl-waw.scw.cloud/communicator
  SCALEWAY_SECRET_TOKEN: ${{secrets.SCALEWAY_SECRET_TOKEN}}
  KUBECONFIG: /home/deploy/config
  KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Login to the Docker repository
        run: docker login $REPO_URL -u nologin -p $SCALEWAY_SECRET_TOKEN
      - name: Build the Docker image
        run: >-
          docker build . --file Dockerfile --tag $REPO_URL/$IMAGE_NAME:latest
          --tag
          $REPO_URL/$IMAGE_NAME:${{steps.package-version.outputs.current-version}}
      - name: Push image to the repository
        run: docker push $REPO_URL/$IMAGE_NAME --all-tags
      - name: Set up kubernetes config
        run: >-
          sudo mkdir -p /home/deploy && echo "${{secrets.KUBE_CONFIG_DATA}}" |
          base64 -d > $KUBECONFIG
      - name: Deploy manifests to prod environment
        run: kubectl apply -f  ./.github/workflows/kubernetes/prod
      - name: Deploy app to dev environment
        run: >-
          kubectl rollout restart deployment communicator-websocket-gateway -n
          communicator-prod
